/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 20/11/2015 16:22:16
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     168000000
#define MX_SYSCLKFreq_VALUE                     168000000
#define MX_HCLKFreq_Value                       168000000
#define MX_FCLKCortexFreq_Value                 168000000
#define MX_CortexFreq_Value                     168000000
#define MX_AHBFreq_Value                        168000000
#define MX_APB1Freq_Value                       42000000
#define MX_APB2Freq_Value                       84000000
#define MX_APB1TimFreq_Value                    42000000
#define MX_APB2TimFreq_Value                    84000000
#define MX_48MHZClocksFreq_Value                48000000
#define MX_EthernetFreq_Value                   168000000
#define MX_I2SClocksFreq_Value                  153600000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    168000000

/*-------------------------------- CAN1       --------------------------------*/

#define MX_CAN1                                 1

/* GPIO Configuration */

/* Pin PB8 */
#define MX_CAN1_RX_GPIO_Speed                   GPIO_SPEED_HIGH
#define MX_CAN1_RX_Pin                          PB8
#define MX_CAN1_RX_GPIOx                        GPIOB
#define MX_CAN1_RX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN1_RX_GPIO_Pin                     GPIO_PIN_8
#define MX_CAN1_RX_GPIO_AF                      GPIO_AF9_CAN1
#define MX_CAN1_RX_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PB9 */
#define MX_CAN1_TX_GPIO_Speed                   GPIO_SPEED_HIGH
#define MX_CAN1_TX_Pin                          PB9
#define MX_CAN1_TX_GPIOx                        GPIOB
#define MX_CAN1_TX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN1_TX_GPIO_Pin                     GPIO_PIN_9
#define MX_CAN1_TX_GPIO_AF                      GPIO_AF9_CAN1
#define MX_CAN1_TX_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- CAN2       --------------------------------*/

#define MX_CAN2                                 1

/* GPIO Configuration */

/* Pin PB12 */
#define MX_CAN2_RX_GPIO_Speed                   GPIO_SPEED_HIGH
#define MX_CAN2_RX_Pin                          PB12
#define MX_CAN2_RX_GPIOx                        GPIOB
#define MX_CAN2_RX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN2_RX_GPIO_Pin                     GPIO_PIN_12
#define MX_CAN2_RX_GPIO_AF                      GPIO_AF9_CAN2
#define MX_CAN2_RX_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PB13 */
#define MX_CAN2_TX_GPIO_Speed                   GPIO_SPEED_HIGH
#define MX_CAN2_TX_Pin                          PB13
#define MX_CAN2_TX_GPIOx                        GPIOB
#define MX_CAN2_TX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN2_TX_GPIO_Pin                     GPIO_PIN_13
#define MX_CAN2_TX_GPIO_AF                      GPIO_AF9_CAN2
#define MX_CAN2_TX_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- CRC        --------------------------------*/

#define MX_CRC                                  1

/* GPIO Configuration */

/*-------------------------------- FSMC       --------------------------------*/

#define MX_FSMC                                 1

/* GPIO Configuration */

/* Pin PE12 */
#define MX_FSMC_D9_DA9_Pin                      PE12
#define MX_FSMC_D9_DA9_GPIOx                    GPIOE
#define MX_FSMC_D9_DA9_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_D9_DA9_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_D9_DA9_GPIO_Pin                 GPIO_PIN_12
#define MX_FSMC_D9_DA9_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_D9_DA9_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PF9 */
#define MX_FSMC_CD_Pin                          PF9
#define MX_FSMC_CD_GPIOx                        GPIOF
#define MX_FSMC_CD_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_CD_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_CD_GPIO_Pin                     GPIO_PIN_9
#define MX_FSMC_CD_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_CD_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PE1 */
#define MX_FSMC_NBL1_Pin                        PE1
#define MX_FSMC_NBL1_GPIOx                      GPIOE
#define MX_FSMC_NBL1_GPIO_PuPd                  GPIO_NOPULL
#define MX_FSMC_NBL1_GPIO_Speed_High_Default    GPIO_SPEED_HIGH
#define MX_FSMC_NBL1_GPIO_Pin                   GPIO_PIN_1
#define MX_FSMC_NBL1_GPIO_AF                    GPIO_AF12_FSMC
#define MX_FSMC_NBL1_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PD9 */
#define MX_FSMC_D14_DA14_Pin                    PD9
#define MX_FSMC_D14_DA14_GPIOx                  GPIOD
#define MX_FSMC_D14_DA14_GPIO_PuPd              GPIO_NOPULL
#define MX_FSMC_D14_DA14_GPIO_Speed_High_Default GPIO_SPEED_HIGH
#define MX_FSMC_D14_DA14_GPIO_Pin               GPIO_PIN_9
#define MX_FSMC_D14_DA14_GPIO_AF                GPIO_AF12_FSMC
#define MX_FSMC_D14_DA14_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PE0 */
#define MX_FSMC_NBL0_Pin                        PE0
#define MX_FSMC_NBL0_GPIOx                      GPIOE
#define MX_FSMC_NBL0_GPIO_PuPd                  GPIO_NOPULL
#define MX_FSMC_NBL0_GPIO_Speed_High_Default    GPIO_SPEED_HIGH
#define MX_FSMC_NBL0_GPIO_Pin                   GPIO_PIN_0
#define MX_FSMC_NBL0_GPIO_AF                    GPIO_AF12_FSMC
#define MX_FSMC_NBL0_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PD8 */
#define MX_FSMC_D13_DA13_Pin                    PD8
#define MX_FSMC_D13_DA13_GPIOx                  GPIOD
#define MX_FSMC_D13_DA13_GPIO_PuPd              GPIO_NOPULL
#define MX_FSMC_D13_DA13_GPIO_Speed_High_Default GPIO_SPEED_HIGH
#define MX_FSMC_D13_DA13_GPIO_Pin               GPIO_PIN_8
#define MX_FSMC_D13_DA13_GPIO_AF                GPIO_AF12_FSMC
#define MX_FSMC_D13_DA13_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PE10 */
#define MX_FSMC_D7_DA7_Pin                      PE10
#define MX_FSMC_D7_DA7_GPIOx                    GPIOE
#define MX_FSMC_D7_DA7_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_D7_DA7_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_D7_DA7_GPIO_Pin                 GPIO_PIN_10
#define MX_FSMC_D7_DA7_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_D7_DA7_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PF7 */
#define MX_FSMC_NREG_Pin                        PF7
#define MX_FSMC_NREG_GPIOx                      GPIOF
#define MX_FSMC_NREG_GPIO_PuPd                  GPIO_NOPULL
#define MX_FSMC_NREG_GPIO_Speed_High_Default    GPIO_SPEED_HIGH
#define MX_FSMC_NREG_GPIO_Pin                   GPIO_PIN_7
#define MX_FSMC_NREG_GPIO_AF                    GPIO_AF12_FSMC
#define MX_FSMC_NREG_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PD15 */
#define MX_FSMC_D1_DA1_Pin                      PD15
#define MX_FSMC_D1_DA1_GPIOx                    GPIOD
#define MX_FSMC_D1_DA1_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_D1_DA1_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_D1_DA1_GPIO_Pin                 GPIO_PIN_15
#define MX_FSMC_D1_DA1_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_D1_DA1_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PE13 */
#define MX_FSMC_D10_DA10_Pin                    PE13
#define MX_FSMC_D10_DA10_GPIOx                  GPIOE
#define MX_FSMC_D10_DA10_GPIO_PuPd              GPIO_NOPULL
#define MX_FSMC_D10_DA10_GPIO_Speed_High_Default GPIO_SPEED_HIGH
#define MX_FSMC_D10_DA10_GPIO_Pin               GPIO_PIN_13
#define MX_FSMC_D10_DA10_GPIO_AF                GPIO_AF12_FSMC
#define MX_FSMC_D10_DA10_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PG9 */
#define MX_FSMC_NCE3_Pin                        PG9
#define MX_FSMC_NCE3_GPIOx                      GPIOG
#define MX_FSMC_NCE3_GPIO_PuPd                  GPIO_NOPULL
#define MX_FSMC_NCE3_GPIO_Speed_High_Default    GPIO_SPEED_HIGH
#define MX_FSMC_NCE3_GPIO_Pin                   GPIO_PIN_9
#define MX_FSMC_NCE3_GPIO_AF                    GPIO_AF12_FSMC
#define MX_FSMC_NCE3_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PD14 */
#define MX_FSMC_D0_DA0_Pin                      PD14
#define MX_FSMC_D0_DA0_GPIOx                    GPIOD
#define MX_FSMC_D0_DA0_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_D0_DA0_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_D0_DA0_GPIO_Pin                 GPIO_PIN_14
#define MX_FSMC_D0_DA0_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_D0_DA0_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PE11 */
#define MX_FSMC_D8_DA8_Pin                      PE11
#define MX_FSMC_D8_DA8_GPIOx                    GPIOE
#define MX_FSMC_D8_DA8_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_D8_DA8_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_D8_DA8_GPIO_Pin                 GPIO_PIN_11
#define MX_FSMC_D8_DA8_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_D8_DA8_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PF6 */
#define MX_FSMC_NIORD_Pin                       PF6
#define MX_FSMC_NIORD_GPIOx                     GPIOF
#define MX_FSMC_NIORD_GPIO_PuPd                 GPIO_NOPULL
#define MX_FSMC_NIORD_GPIO_Speed_High_Default   GPIO_SPEED_HIGH
#define MX_FSMC_NIORD_GPIO_Pin                  GPIO_PIN_6
#define MX_FSMC_NIORD_GPIO_AF                   GPIO_AF12_FSMC
#define MX_FSMC_NIORD_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF14 */
#define MX_FSMC_A8_Pin                          PF14
#define MX_FSMC_A8_GPIOx                        GPIOF
#define MX_FSMC_A8_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_A8_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_A8_GPIO_Pin                     GPIO_PIN_14
#define MX_FSMC_A8_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_A8_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF13 */
#define MX_FSMC_A7_Pin                          PF13
#define MX_FSMC_A7_GPIOx                        GPIOF
#define MX_FSMC_A7_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_A7_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_A7_GPIO_Pin                     GPIO_PIN_13
#define MX_FSMC_A7_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_A7_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF12 */
#define MX_FSMC_A6_Pin                          PF12
#define MX_FSMC_A6_GPIOx                        GPIOF
#define MX_FSMC_A6_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_A6_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_A6_GPIO_Pin                     GPIO_PIN_12
#define MX_FSMC_A6_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_A6_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF5 */
#define MX_FSMC_A5_Pin                          PF5
#define MX_FSMC_A5_GPIOx                        GPIOF
#define MX_FSMC_A5_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_A5_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_A5_GPIO_Pin                     GPIO_PIN_5
#define MX_FSMC_A5_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_A5_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF15 */
#define MX_FSMC_A9_Pin                          PF15
#define MX_FSMC_A9_GPIOx                        GPIOF
#define MX_FSMC_A9_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_A9_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_A9_GPIO_Pin                     GPIO_PIN_15
#define MX_FSMC_A9_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_A9_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD11 */
#define MX_FSMC_A16_CLE_Pin                     PD11
#define MX_FSMC_A16_CLE_GPIOx                   GPIOD
#define MX_FSMC_A16_CLE_GPIO_PuPd               GPIO_NOPULL
#define MX_FSMC_A16_CLE_GPIO_Speed_High_Default GPIO_SPEED_HIGH
#define MX_FSMC_A16_CLE_GPIO_Pin                GPIO_PIN_11
#define MX_FSMC_A16_CLE_GPIO_AF                 GPIO_AF12_FSMC
#define MX_FSMC_A16_CLE_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PD7 */
#define MX_FSMC_NE1_Pin                         PD7
#define MX_FSMC_NE1_GPIOx                       GPIOD
#define MX_FSMC_NE1_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_NE1_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_NE1_GPIO_Pin                    GPIO_PIN_7
#define MX_FSMC_NE1_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_NE1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PD12 */
#define MX_FSMC_A17_ALE_Pin                     PD12
#define MX_FSMC_A17_ALE_GPIOx                   GPIOD
#define MX_FSMC_A17_ALE_GPIO_PuPd               GPIO_NOPULL
#define MX_FSMC_A17_ALE_GPIO_Speed_High_Default GPIO_SPEED_HIGH
#define MX_FSMC_A17_ALE_GPIO_Pin                GPIO_PIN_12
#define MX_FSMC_A17_ALE_GPIO_AF                 GPIO_AF12_FSMC
#define MX_FSMC_A17_ALE_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PE8 */
#define MX_FSMC_D5_DA5_Pin                      PE8
#define MX_FSMC_D5_DA5_GPIOx                    GPIOE
#define MX_FSMC_D5_DA5_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_D5_DA5_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_D5_DA5_GPIO_Pin                 GPIO_PIN_8
#define MX_FSMC_D5_DA5_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_D5_DA5_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PG14 */
#define MX_FSMC_A25_Pin                         PG14
#define MX_FSMC_A25_GPIOx                       GPIOG
#define MX_FSMC_A25_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A25_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A25_GPIO_Pin                    GPIO_PIN_14
#define MX_FSMC_A25_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A25_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PE9 */
#define MX_FSMC_D6_DA6_Pin                      PE9
#define MX_FSMC_D6_DA6_GPIOx                    GPIOE
#define MX_FSMC_D6_DA6_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_D6_DA6_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_D6_DA6_GPIO_Pin                 GPIO_PIN_9
#define MX_FSMC_D6_DA6_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_D6_DA6_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PF10 */
#define MX_FSMC_INTR_Pin                        PF10
#define MX_FSMC_INTR_GPIOx                      GPIOF
#define MX_FSMC_INTR_GPIO_PuPd                  GPIO_NOPULL
#define MX_FSMC_INTR_GPIO_Speed_High_Default    GPIO_SPEED_HIGH
#define MX_FSMC_INTR_GPIO_Pin                   GPIO_PIN_10
#define MX_FSMC_INTR_GPIO_AF                    GPIO_AF12_FSMC
#define MX_FSMC_INTR_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PF0 */
#define MX_FSMC_A0_Pin                          PF0
#define MX_FSMC_A0_GPIOx                        GPIOF
#define MX_FSMC_A0_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_A0_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_A0_GPIO_Pin                     GPIO_PIN_0
#define MX_FSMC_A0_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_A0_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PE14 */
#define MX_FSMC_D11_DA11_Pin                    PE14
#define MX_FSMC_D11_DA11_GPIOx                  GPIOE
#define MX_FSMC_D11_DA11_GPIO_PuPd              GPIO_NOPULL
#define MX_FSMC_D11_DA11_GPIO_Speed_High_Default GPIO_SPEED_HIGH
#define MX_FSMC_D11_DA11_GPIO_Pin               GPIO_PIN_14
#define MX_FSMC_D11_DA11_GPIO_AF                GPIO_AF12_FSMC
#define MX_FSMC_D11_DA11_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PE4 */
#define MX_FSMC_A20_Pin                         PE4
#define MX_FSMC_A20_GPIOx                       GPIOE
#define MX_FSMC_A20_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A20_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A20_GPIO_Pin                    GPIO_PIN_4
#define MX_FSMC_A20_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A20_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PE5 */
#define MX_FSMC_A21_Pin                         PE5
#define MX_FSMC_A21_GPIOx                       GPIOE
#define MX_FSMC_A21_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A21_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A21_GPIO_Pin                    GPIO_PIN_5
#define MX_FSMC_A21_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A21_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PF4 */
#define MX_FSMC_A4_Pin                          PF4
#define MX_FSMC_A4_GPIOx                        GPIOF
#define MX_FSMC_A4_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_A4_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_A4_GPIO_Pin                     GPIO_PIN_4
#define MX_FSMC_A4_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_A4_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PE6 */
#define MX_FSMC_A22_Pin                         PE6
#define MX_FSMC_A22_GPIOx                       GPIOE
#define MX_FSMC_A22_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A22_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A22_GPIO_Pin                    GPIO_PIN_6
#define MX_FSMC_A22_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A22_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PF3 */
#define MX_FSMC_A3_Pin                          PF3
#define MX_FSMC_A3_GPIOx                        GPIOF
#define MX_FSMC_A3_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_A3_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_A3_GPIO_Pin                     GPIO_PIN_3
#define MX_FSMC_A3_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_A3_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PE2 */
#define MX_FSMC_A23_Pin                         PE2
#define MX_FSMC_A23_GPIOx                       GPIOE
#define MX_FSMC_A23_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A23_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A23_GPIO_Pin                    GPIO_PIN_2
#define MX_FSMC_A23_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A23_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PF2 */
#define MX_FSMC_A2_Pin                          PF2
#define MX_FSMC_A2_GPIOx                        GPIOF
#define MX_FSMC_A2_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_A2_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_A2_GPIO_Pin                     GPIO_PIN_2
#define MX_FSMC_A2_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_A2_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PF1 */
#define MX_FSMC_A1_Pin                          PF1
#define MX_FSMC_A1_GPIOx                        GPIOF
#define MX_FSMC_A1_GPIO_PuPd                    GPIO_NOPULL
#define MX_FSMC_A1_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_FSMC_A1_GPIO_Pin                     GPIO_PIN_1
#define MX_FSMC_A1_GPIO_AF                      GPIO_AF12_FSMC
#define MX_FSMC_A1_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PG13 */
#define MX_FSMC_A24_Pin                         PG13
#define MX_FSMC_A24_GPIOx                       GPIOG
#define MX_FSMC_A24_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A24_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A24_GPIO_Pin                    GPIO_PIN_13
#define MX_FSMC_A24_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A24_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PD0 */
#define MX_FSMC_D2_DA2_Pin                      PD0
#define MX_FSMC_D2_DA2_GPIOx                    GPIOD
#define MX_FSMC_D2_DA2_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_D2_DA2_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_D2_DA2_GPIO_Pin                 GPIO_PIN_0
#define MX_FSMC_D2_DA2_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_D2_DA2_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PG11 */
#define MX_FSMC_NCE4_2_Pin                      PG11
#define MX_FSMC_NCE4_2_GPIOx                    GPIOG
#define MX_FSMC_NCE4_2_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_NCE4_2_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_NCE4_2_GPIO_Pin                 GPIO_PIN_11
#define MX_FSMC_NCE4_2_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_NCE4_2_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PG10 */
#define MX_FSMC_NCE4_1_Pin                      PG10
#define MX_FSMC_NCE4_1_GPIOx                    GPIOG
#define MX_FSMC_NCE4_1_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_NCE4_1_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_NCE4_1_GPIO_Pin                 GPIO_PIN_10
#define MX_FSMC_NCE4_1_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_NCE4_1_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PG4 */
#define MX_FSMC_A14_Pin                         PG4
#define MX_FSMC_A14_GPIOx                       GPIOG
#define MX_FSMC_A14_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A14_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A14_GPIO_Pin                    GPIO_PIN_4
#define MX_FSMC_A14_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A14_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PG5 */
#define MX_FSMC_A15_Pin                         PG5
#define MX_FSMC_A15_GPIOx                       GPIOG
#define MX_FSMC_A15_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A15_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A15_GPIO_Pin                    GPIO_PIN_5
#define MX_FSMC_A15_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A15_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PD4 */
#define MX_FSMC_NOE_Pin                         PD4
#define MX_FSMC_NOE_GPIOx                       GPIOD
#define MX_FSMC_NOE_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_NOE_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_NOE_GPIO_Pin                    GPIO_PIN_4
#define MX_FSMC_NOE_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_NOE_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PD1 */
#define MX_FSMC_D3_DA3_Pin                      PD1
#define MX_FSMC_D3_DA3_GPIOx                    GPIOD
#define MX_FSMC_D3_DA3_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_D3_DA3_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_D3_DA3_GPIO_Pin                 GPIO_PIN_1
#define MX_FSMC_D3_DA3_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_D3_DA3_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PD10 */
#define MX_FSMC_D15_DA15_Pin                    PD10
#define MX_FSMC_D15_DA15_GPIOx                  GPIOD
#define MX_FSMC_D15_DA15_GPIO_PuPd              GPIO_NOPULL
#define MX_FSMC_D15_DA15_GPIO_Speed_High_Default GPIO_SPEED_HIGH
#define MX_FSMC_D15_DA15_GPIO_Pin               GPIO_PIN_10
#define MX_FSMC_D15_DA15_GPIO_AF                GPIO_AF12_FSMC
#define MX_FSMC_D15_DA15_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PD13 */
#define MX_FSMC_A18_Pin                         PD13
#define MX_FSMC_A18_GPIOx                       GPIOD
#define MX_FSMC_A18_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A18_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A18_GPIO_Pin                    GPIO_PIN_13
#define MX_FSMC_A18_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A18_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PE3 */
#define MX_FSMC_A19_Pin                         PE3
#define MX_FSMC_A19_GPIOx                       GPIOE
#define MX_FSMC_A19_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A19_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A19_GPIO_Pin                    GPIO_PIN_3
#define MX_FSMC_A19_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A19_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PE15 */
#define MX_FSMC_D12_DA12_Pin                    PE15
#define MX_FSMC_D12_DA12_GPIOx                  GPIOE
#define MX_FSMC_D12_DA12_GPIO_PuPd              GPIO_NOPULL
#define MX_FSMC_D12_DA12_GPIO_Speed_High_Default GPIO_SPEED_HIGH
#define MX_FSMC_D12_DA12_GPIO_Pin               GPIO_PIN_15
#define MX_FSMC_D12_DA12_GPIO_AF                GPIO_AF12_FSMC
#define MX_FSMC_D12_DA12_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PD6 */
#define MX_FSMC_NWAIT_Pin                       PD6
#define MX_FSMC_NWAIT_GPIOx                     GPIOD
#define MX_FSMC_NWAIT_GPIO_PuPd                 GPIO_NOPULL
#define MX_FSMC_NWAIT_GPIO_Speed_High_Default   GPIO_SPEED_HIGH
#define MX_FSMC_NWAIT_GPIO_Pin                  GPIO_PIN_6
#define MX_FSMC_NWAIT_GPIO_AF                   GPIO_AF12_FSMC
#define MX_FSMC_NWAIT_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF8 */
#define MX_FSMC_NIOWR_Pin                       PF8
#define MX_FSMC_NIOWR_GPIOx                     GPIOF
#define MX_FSMC_NIOWR_GPIO_PuPd                 GPIO_NOPULL
#define MX_FSMC_NIOWR_GPIO_Speed_High_Default   GPIO_SPEED_HIGH
#define MX_FSMC_NIOWR_GPIO_Pin                  GPIO_PIN_8
#define MX_FSMC_NIOWR_GPIO_AF                   GPIO_AF12_FSMC
#define MX_FSMC_NIOWR_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD5 */
#define MX_FSMC_NWE_Pin                         PD5
#define MX_FSMC_NWE_GPIOx                       GPIOD
#define MX_FSMC_NWE_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_NWE_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_NWE_GPIO_Pin                    GPIO_PIN_5
#define MX_FSMC_NWE_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_NWE_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PE7 */
#define MX_FSMC_D4_DA4_Pin                      PE7
#define MX_FSMC_D4_DA4_GPIOx                    GPIOE
#define MX_FSMC_D4_DA4_GPIO_PuPd                GPIO_NOPULL
#define MX_FSMC_D4_DA4_GPIO_Speed_High_Default  GPIO_SPEED_HIGH
#define MX_FSMC_D4_DA4_GPIO_Pin                 GPIO_PIN_7
#define MX_FSMC_D4_DA4_GPIO_AF                  GPIO_AF12_FSMC
#define MX_FSMC_D4_DA4_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PG0 */
#define MX_FSMC_A10_Pin                         PG0
#define MX_FSMC_A10_GPIOx                       GPIOG
#define MX_FSMC_A10_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A10_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A10_GPIO_Pin                    GPIO_PIN_0
#define MX_FSMC_A10_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A10_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PG1 */
#define MX_FSMC_A11_Pin                         PG1
#define MX_FSMC_A11_GPIOx                       GPIOG
#define MX_FSMC_A11_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A11_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A11_GPIO_Pin                    GPIO_PIN_1
#define MX_FSMC_A11_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A11_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PG2 */
#define MX_FSMC_A12_Pin                         PG2
#define MX_FSMC_A12_GPIOx                       GPIOG
#define MX_FSMC_A12_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A12_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A12_GPIO_Pin                    GPIO_PIN_2
#define MX_FSMC_A12_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A12_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PG3 */
#define MX_FSMC_A13_Pin                         PG3
#define MX_FSMC_A13_GPIOx                       GPIOG
#define MX_FSMC_A13_GPIO_PuPd                   GPIO_NOPULL
#define MX_FSMC_A13_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_FSMC_A13_GPIO_Pin                    GPIO_PIN_3
#define MX_FSMC_A13_GPIO_AF                     GPIO_AF12_FSMC
#define MX_FSMC_A13_GPIO_Mode                   GPIO_MODE_AF_PP

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB6 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_I2C1_SCL_Pin                         PB6
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_6
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- I2C2       --------------------------------*/

#define MX_I2C2                                 1

/* GPIO Configuration */

/* Pin PB11 */
#define MX_I2C2_SDA_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_I2C2_SDA_Pin                         PB11
#define MX_I2C2_SDA_GPIOx                       GPIOB
#define MX_I2C2_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C2_SDA_GPIO_Pin                    GPIO_PIN_11
#define MX_I2C2_SDA_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB10 */
#define MX_I2C2_SCL_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_I2C2_SCL_Pin                         PB10
#define MX_I2C2_SCL_GPIOx                       GPIOB
#define MX_I2C2_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C2_SCL_GPIO_Pin                    GPIO_PIN_10
#define MX_I2C2_SCL_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- RNG        --------------------------------*/

#define MX_RNG                                  1

/* GPIO Configuration */

/*-------------------------------- SDIO       --------------------------------*/

#define MX_SDIO                                 1

/* GPIO Configuration */

/* Pin PD2 */
#define MX_SDIO_CMD_Pin                         PD2
#define MX_SDIO_CMD_GPIOx                       GPIOD
#define MX_SDIO_CMD_GPIO_PuPd                   GPIO_NOPULL
#define MX_SDIO_CMD_GPIO_Speed_High_Default     GPIO_SPEED_HIGH
#define MX_SDIO_CMD_GPIO_Pin                    GPIO_PIN_2
#define MX_SDIO_CMD_GPIO_AF                     GPIO_AF12_SDIO
#define MX_SDIO_CMD_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC12 */
#define MX_SDIO_CK_Pin                          PC12
#define MX_SDIO_CK_GPIOx                        GPIOC
#define MX_SDIO_CK_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_CK_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_SDIO_CK_GPIO_Pin                     GPIO_PIN_12
#define MX_SDIO_CK_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_CK_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC8 */
#define MX_SDIO_D0_Pin                          PC8
#define MX_SDIO_D0_GPIOx                        GPIOC
#define MX_SDIO_D0_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D0_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_SDIO_D0_GPIO_Pin                     GPIO_PIN_8
#define MX_SDIO_D0_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D0_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC9 */
#define MX_SDIO_D1_Pin                          PC9
#define MX_SDIO_D1_GPIOx                        GPIOC
#define MX_SDIO_D1_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D1_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_SDIO_D1_GPIO_Pin                     GPIO_PIN_9
#define MX_SDIO_D1_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D1_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC10 */
#define MX_SDIO_D2_Pin                          PC10
#define MX_SDIO_D2_GPIOx                        GPIOC
#define MX_SDIO_D2_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D2_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_SDIO_D2_GPIO_Pin                     GPIO_PIN_10
#define MX_SDIO_D2_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D2_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC11 */
#define MX_SDIO_D3_Pin                          PC11
#define MX_SDIO_D3_GPIOx                        GPIOC
#define MX_SDIO_D3_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D3_GPIO_Speed_High_Default      GPIO_SPEED_HIGH
#define MX_SDIO_D3_GPIO_Pin                     GPIO_PIN_11
#define MX_SDIO_D3_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D3_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- SPI1       --------------------------------*/

#define MX_SPI1                                 1

/* GPIO Configuration */

/* Pin PA6 */
#define MX_SPI1_MISO_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_SPI1_MISO_Pin                        PA6
#define MX_SPI1_MISO_GPIOx                      GPIOA
#define MX_SPI1_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI1_MISO_GPIO_Pin                   GPIO_PIN_6
#define MX_SPI1_MISO_GPIO_AF                    GPIO_AF5_SPI1
#define MX_SPI1_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA7 */
#define MX_SPI1_MOSI_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_SPI1_MOSI_Pin                        PA7
#define MX_SPI1_MOSI_GPIOx                      GPIOA
#define MX_SPI1_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI1_MOSI_GPIO_Pin                   GPIO_PIN_7
#define MX_SPI1_MOSI_GPIO_AF                    GPIO_AF5_SPI1
#define MX_SPI1_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA5 */
#define MX_SPI1_SCK_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_SPI1_SCK_Pin                         PA5
#define MX_SPI1_SCK_GPIOx                       GPIOA
#define MX_SPI1_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI1_SCK_GPIO_Pin                    GPIO_PIN_5
#define MX_SPI1_SCK_GPIO_AF                     GPIO_AF5_SPI1
#define MX_SPI1_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/*-------------------------------- UART4      --------------------------------*/

#define MX_UART4                                1

#define MX_UART4_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PA1 */
#define MX_UART4_RX_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_UART4_RX_Pin                         PA1
#define MX_UART4_RX_GPIOx                       GPIOA
#define MX_UART4_RX_GPIO_PuPd                   GPIO_PULLUP
#define MX_UART4_RX_GPIO_Pin                    GPIO_PIN_1
#define MX_UART4_RX_GPIO_AF                     GPIO_AF8_UART4
#define MX_UART4_RX_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PA0-WKUP */
#define MX_UART4_TX_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_UART4_TX_Pin                         PA0-WKUP
#define MX_UART4_TX_GPIOx                       GPIOA
#define MX_UART4_TX_GPIO_PuPd                   GPIO_PULLUP
#define MX_UART4_TX_GPIO_Pin                    GPIO_PIN_0
#define MX_UART4_TX_GPIO_AF                     GPIO_AF8_UART4
#define MX_UART4_TX_GPIO_Mode                   GPIO_MODE_AF_PP

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_SYNC

/* GPIO Configuration */

/* Pin PA2 */
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_USART2_TX_Pin                        PA2
#define MX_USART2_TX_GPIOx                      GPIOA
#define MX_USART2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART2_TX_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA3 */
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_USART2_RX_Pin                        PA3
#define MX_USART2_RX_GPIOx                      GPIOA
#define MX_USART2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_3
#define MX_USART2_RX_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA4 */
#define MX_USART2_CK_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_USART2_CK_Pin                        PA4
#define MX_USART2_CK_GPIOx                      GPIOA
#define MX_USART2_CK_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_CK_GPIO_Pin                   GPIO_PIN_4
#define MX_USART2_CK_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_CK_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- USART6     --------------------------------*/

#define MX_USART6                               1

#define MX_USART6_VM                            VM_SYNC

/* GPIO Configuration */

/* Pin PG7 */
#define MX_USART6_CK_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_USART6_CK_Pin                        PG7
#define MX_USART6_CK_GPIOx                      GPIOG
#define MX_USART6_CK_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART6_CK_GPIO_Pin                   GPIO_PIN_7
#define MX_USART6_CK_GPIO_AF                    GPIO_AF8_USART6
#define MX_USART6_CK_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC7 */
#define MX_USART6_RX_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_USART6_RX_Pin                        PC7
#define MX_USART6_RX_GPIOx                      GPIOC
#define MX_USART6_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART6_RX_GPIO_Pin                   GPIO_PIN_7
#define MX_USART6_RX_GPIO_AF                    GPIO_AF8_USART6
#define MX_USART6_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PC6 */
#define MX_USART6_TX_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_USART6_TX_Pin                        PC6
#define MX_USART6_TX_GPIOx                      GPIOC
#define MX_USART6_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART6_TX_GPIO_Pin                   GPIO_PIN_6
#define MX_USART6_TX_GPIO_AF                    GPIO_AF8_USART6
#define MX_USART6_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- USB_OTG_FS --------------------------------*/

#define MX_USB_OTG_FS                           1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_USB_OTG_FS_DM_GPIO_Speed             GPIO_SPEED_HIGH
#define MX_USB_OTG_FS_DM_Pin                    PA11
#define MX_USB_OTG_FS_DM_GPIOx                  GPIOA
#define MX_USB_OTG_FS_DM_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_FS_DM_GPIO_Pin               GPIO_PIN_11
#define MX_USB_OTG_FS_DM_GPIO_AF                GPIO_AF10_OTG_FS
#define MX_USB_OTG_FS_DM_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PA12 */
#define MX_USB_OTG_FS_DP_GPIO_Speed             GPIO_SPEED_HIGH
#define MX_USB_OTG_FS_DP_Pin                    PA12
#define MX_USB_OTG_FS_DP_GPIOx                  GPIOA
#define MX_USB_OTG_FS_DP_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_FS_DP_GPIO_Pin               GPIO_PIN_12
#define MX_USB_OTG_FS_DP_GPIO_AF                GPIO_AF10_OTG_FS
#define MX_USB_OTG_FS_DP_GPIO_Mode              GPIO_MODE_AF_PP

/* Pin PA10 */
#define MX_USB_OTG_FS_ID_GPIO_Speed             GPIO_SPEED_HIGH
#define MX_USB_OTG_FS_ID_Pin                    PA10
#define MX_USB_OTG_FS_ID_GPIOx                  GPIOA
#define MX_USB_OTG_FS_ID_GPIO_PuPd              GPIO_NOPULL
#define MX_USB_OTG_FS_ID_GPIO_Pin               GPIO_PIN_10
#define MX_USB_OTG_FS_ID_GPIO_AF                GPIO_AF10_OTG_FS
#define MX_USB_OTG_FS_ID_GPIO_Mode              GPIO_MODE_AF_PP

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

