# Find Precision Missions library
find_path(PRECISION_MISSIONS_INCLUDE_DIR
  OnboardSDK.h
  HINTS ${PRECISION_MISSIONS_INCLUDE_DIR}
  NO_DEFAULT_PATH)

find_path(PRECISION_MISSIONS_DEPENDENCIES_DIR
  Eigen/Dense
  HINTS ${PRECISION_MISSIONS_DEPENDENCIES_DIR}
  NO_DEFAULT_PATH)

set(PRECISION_MISSIONS_LIBRARY_NAMES "libmissionplan.a")
find_library(PRECISION_MISSIONS_LIBRARY
  NAMES ${LIBLAS_NAMES}
  HINTS ${PRECISION_MISSIONS_LIBRARY}
  NO_DEFAULT_PATH)

if(EXISTS ${PRECISION_MISSIONS_INCLUDE_DIR})
  message(STATUS "Precision Missions include dir set to ${PRECISION_MISSIONS_INCLUDE_DIR}")
endif()

if(EXISTS ${PRECISION_MISSIONS_DEPENDENCIES_DIR})
  message(STATUS "Precision Missions dependencies dir set to ${PRECISION_MISSIONS_DEPENDENCIES_DIR}")
endif()

if(EXISTS ${PRECISION_MISSIONS_LIBRARY})
  message(STATUS "Precision Missions library set to ${PRECISION_MISSIONS_LIBRARY}")
  set(PrecisionMissions_FOUND "YES")
endif()

