#latitude is in degree
float64 latitude
#longitude is in degree
float64 longitude
float32 altitude
---
bool result
---
#progress is in percent
uint8 latitude_progress
uint8 longitude_progress
uint8 altitude_progress
