include(ExternalProject)
message( "External project - VTK" )

IF(CMAKE_EXTRA_GENERATOR)
  SET(cmake_gen "${CMAKE_EXTRA_GENERATOR} - ${CMAKE_GENERATOR}")
ELSE()
  SET(cmake_gen "${CMAKE_GENERATOR}")
ENDIF()

ExternalProject_Add(VTK
  GIT_REPOSITORY http://vtk.org/VTK.git
  GIT_TAG v7.0.0
  SOURCE_DIR VTK
  BINARY_DIR VTK-build
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CMAKE_GENERATOR ${cmake_gen}
  CMAKE_ARGS
    -DBUILD_EXAMPLES:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DBUILD_TESTING:BOOL=OFF
    -DCMAKE_BUILD_TYPE:STRING=${BUILD_TYPE}
    -DVTK_BUILD_ALL_MODULES:BOOL=OFF
    -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_DEPENDENCIES_DIR}
)

